Repository jenkinsci/pipeline-input-step-plugin, pull requests merged in 2021-12, with the labels that each got.

#52 Update plugin POM and BOM
  .mvn/extensions.xml
  pom.xml
Labels: dependencies

#57 Use container agent in `Jenkinsfile`
  Jenkinsfile
Labels: tests

#61 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: internal

#62 update changelog and readme
  CHANGELOG.md
  README.md
Labels: documentation
