Repository jenkinsci/pipeline-input-step-plugin, pull requests merged in 2022-01, with the labels that each got.

#67 EOL JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/ApproverAction.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputAction.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputSubmittedAction.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/Rejection.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java
Labels: chore

#53 Fix documentation typo for options available in stage view
  src/main/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStep/help.html
Labels: documentation

#65 Reduce usages of Guava
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
Labels: dependencies

#70 Bump parent POM
  pom.xml
Labels: dependencies

#69 Stop using Guice to inject `InputStep` & context parameters
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest.java
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/1/build.xml
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/1/log
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/1/log-index
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/1/program.dat
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/1/workflow/2.xml
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/1/workflow/3.xml
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/legacyIds
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/builds/permalinks
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/config.xml
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/jobs/p/nextBuildNumber
  src/test/resources/org/jenkinsci/plugins/workflow/support/steps/input/InputStepTest/serialForm/org.jenkinsci.plugins.workflow.flow.FlowExecutionList.xml
Labels: bug
